
name: Run FPL Prediction

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # This runs the job daily at midnight (optional)

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Install Python dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run the Python script
    - name: Run FPL Prediction
      run: |
        #python ./Vis/pages/Prediction/model.py
        #python ./FPL/transfer_collection.py
        python ./FPL/Total_managers.py

    # Commit and push changes (if any)
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Update  Files"
          git push
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
