name: Run FPL Prediction

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # This runs the job daily at midnight (optional)

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Install Python dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run the Python script
    - name: Run FPL Prediction
      run: |
        python ./Vis/pages/Prediction/model.py

    # Commit and push changes
    - name: Commit and push changes
      run: |
        git config --global user.name 'xRayzox'
        git config --global user.email 'wael.hcine@esprit.tn'
        git init
        git add ./Vis/pages/Prediction
        git commit -m "Update prediction results"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
